### ISSUE TITLE
BWAPI.lib was created with older compiler

### ISSUE THREAD

**Issue by Crasher07** [bwapi/bwapi#797]
I am requesting a new build as mentioned on the release page... received error when compiling the BWAPI_Setup.VS.15.7.3.exe file:
"LINK : fatal error C1047: The object or library file '..\lib\BWAPI.lib' was created with an older compiler than other objects; rebuild old objects and libraries"
Using VS17 v.15.8.1; Windows SDK Version 10.0.17134.0

**Comment by heinermann** [comment]
Can you try https://ci.appveyor.com/project/heinermann/bwapi/build/4.2.0.106/artifacts ?

Also please complain to Microsoft.

**Comment by Crasher07** [comment]
Thanks.  Same issue... should I have to change Windows SDK Version from 8.1 to 10.0.17134.0?
![image](https://user-images.githubusercontent.com/42505662/44305140-8df8e900-a33e-11e8-8ef3-5e7153068810.png)

**Comment by HelpMe1117** [comment]
I'm also having the same issue after updating visual studio from V15.7.3 to V15.8.1.

**Comment by Crasher07** [comment]
gotta love MS!
I complained to MS... here's the link in case you (or anyone else) wants to vote for it...
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/35154427-ensure-backwards-library-compatibility-within-majo

**Comment by heinermann** [comment]
It looks like AppVeyor is still using 15.7.x unfortunately. I would either have to build BWAPI manually or wait. You could try building BWAPILib with your bot as a workaround.

**Comment by N00byEdge** [comment]
Yes, the recommended setup is to add all your prerequisites as dependencies to your solution as subprojects. Problem is that the NoCopy project configurations only are on the `develop` branch. They make integration into your solution much easier. This means you probably have to add your bot to the BWAPI solution unless you're working off of `develop`.

**Comment by N00byEdge** [comment]
@Crasher07 You need to clone the git repo. That file is generated from the BWAPI git metadata. This is a horrible solution but that's how it works at this moment.

**Comment by N00byEdge** [comment]
You should also be able to just open BWAPI.sln after cloning and start coding right away.

**Comment by kikwon** [comment]
Could you tell me specific guide for me? I got the same issue, but I don't have any idea.

**Comment by ChobitsTheZero** [comment]
> "Horrible" would be an apt description. Finally got it to work. Thanks for the help!
> 
> For others who may have this issue and want to manually build the BWAPI.lib file:
> 
> 1. clone the git repo
> 2. download and run the BWAPI_Setup.VS.15.7.3.exe file.
> 3. copy Debug.h, starcraftver.h, and svnrev.h from the cloned files to the extracted setup files
> 4. build BWAPILIB.vcxproj - I got XCOPY errors and had to change the directory where it looks (right click properties on BWAPILIB project, under the Build Events => Pre-Link Event => Command Line section).
> 5. open BWAPI\ExampleProjects.sln and build
>    Then run chaoslauncher and have fun!

I am unable to locate svnrev.h, could you specify its location?

Was able to locate Debug.h and starcraftver.h, just missing svnrev.h

**Comment by ratiotile** [comment]
@ChobitsTheZero svnrev.h is generated during the build process. You should just build the entire solution (not just BWAPILIB), since each project has dependencies - if those projects haven't been built yet, the files won't be found because they haven't been generated yet.
